### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by rodohanna** [mxenabled/path-core#7]
As of now, we only publish artifacts to JitPack.io. Ideally, we would also publish artifacts to [Maven Central](https://mvnrepository.com/). 

Maven Central provides an official guide here -> https://maven.apache.org/repository/guide-central-repository-upload.html

Here is an additional guide that might be helpful -> https://dzone.com/articles/how-to-publish-artifacts-to-maven-central

**Comment by mattnichols** [comment]
Complete. @rodohanna is super jealous!
